run_mode: "ft"
load_model: True
load_dir: "/storage1/christopherking/Active/jerry.kong/saved_exp/2024-08-21 16:08:39.060649_656/mem_ckpt.pth"
#load_dir: "/storage1/christopherking/Active/jerry.kong/saved_exp/2024-08-24 02:11:49.665052_351/best_ckpt.pth"
#load_dir: "/storage1/christopherking/Active/jerry.kong/saved_exp/2024-08-24 11:45:59.507954_049/best_ckpt.pth"
#load_dir: "/storage1/christopherking/Active/jerry.kong/saved_exp/2024-08-25 01:53:47.943422_368/best_ckpt.pth"
#load_dir: "/storage1/christopherking/Active/jerry.kong/saved_exp/2024-08-26 00:00:18.003550_592/best_ckpt.pth"
#load_dir: "/storage1/christopherking/Active/jerry.kong/saved_exp/2024-09-10 17:21:46.136630_953/best_ckpt.pth" #link
grad_acc_step: 32
last_epochs: 0
num_epochs: 1
mode: autoencoder
batch_size: 1
lr: 0.0001
l2: 0.0
selections: True
llm_max_length: 256

train_task_names:
  - arxiv_link
  - arxiv
  - pubmed_node
  - pubmed_link
sample_size_per_task:
  - 80000
  - 40000
  - 10000
  - 40000
hops:
  - 3
  - 3
  - 3
  - 3

train_max_nodes_per_hops:
  - 5
  - 5
  - 5
  - 5
ways: 10
instructs: True

eval_task_names:
#  - cora_node
#  - pubmed_node
#  - wikics
#  - products
#  - expla_graph
#  - fb15k237
#  - scene_graph
  - pubmed_link
  - pubmed_node
  - cora_link
  - cora_node
  - arxiv_link
  - arxiv
inf_sample_size_per_task: 500
inf_hops:
#  - 3
#  - 3
#  - 3
#  - 3
#  - -1
#  - 3
#  - -1
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3

inf_max_nodes_per_hops:
#  - 10
#  - 10
#  - 10
#  - 10
#  - -1
#  - 10
#  - -1
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10

inf_ways:
#  - 7
#  - 3
#  - 10
#  - 10
#  - 2
#  - 10
#  - -1
  - 2
  - 3
  - 2
  - 7
  - 2
  - 40

inf_instructs:
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
  - True
  - True
  - True
  - True
  - True
  - True

inf_selections:
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
  - True
  - True
  - True
  - True
  - True
  - True

dec_lora: True