run_mode: "ft"
load_model: True
load_dir: "/storage1/christopherking/Active/jerry.kong/saved_exp/2024-07-24 23:21:50.320791_779/mem_ckpt.pth"
grad_acc_step: 64
last_epochs: 0
num_epochs: 1
mode: autoencoder
batch_size: 1
lr: 0.0001
l2: 0.0
selections: True
llm_max_length: 256

train_task_names:
  - arxiv
sample_size_per_task:
  - 80000
hops:
  - 3

train_max_nodes_per_hops:
  - 5
ways: 10
instructs: True

eval_task_names:
  - cora_node
  - pubmed_node
  - wikics
  - products
  - expla_graph
  - fb15k237
  - scene_graph
inf_sample_size_per_task: 500
inf_hops:
  - 3
  - 3
  - 3
  - 3
  - -1
  - 3
  - -1

inf_max_nodes_per_hops:
  - 10
  - 10
  - 10
  - 10
  - -1
  - 10
  - -1

inf_ways:
  - 7
  - 3
  - 10
  - 10
  - 2
  - 10
  - -1

inf_instructs:
  - True
  - True
  - True
  - True
  - True
  - True
  - True

inf_selections:
  - True
  - True
  - True
  - True
  - True
  - True
  - True

dec_lora: True