run_mode: "ft"
load_model: True
load_dir: "mem_ckpt.pth"
grad_acc_step: 32
last_epochs: 0
num_epochs: 1
mode: autoencoder
batch_size: 1
lr: 0.0001
l2: 0.0
llm_max_length: 256

train_task_names:
  - mag240m
  - wikikg90m
  - arxiv_link
  - arxiv
  - pubmed_node
  - pubmed_link

sample_size_per_task:
  - 100000
  - 100000
  - 40000
  - 50000
  - 5000
  - 5000
hops:
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3

train_max_nodes_per_hops:
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
ways: 10
instructs: True
selections: True

eval_task_names:
#  - cora_node
#  - pubmed_node
#  - wikics
#  - products
#  - expla_graph
#  - fb15k237
#  - scene_graph
  - pubmed_link
  - pubmed_node
  - cora_link
  - cora_node
  - arxiv_link
  - arxiv
inf_sample_size_per_task: 500
inf_hops:
#  - 3
#  - 3
#  - 3
#  - 3
#  - -1
#  - 3
#  - -1
  - 3
  - 3
  - 3
  - 3
  - 3
  - 3

inf_max_nodes_per_hops:
#  - 10
#  - 10
#  - 10
#  - 10
#  - -1
#  - 10
#  - -1
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10

inf_ways:
#  - 7
#  - 3
#  - 10
#  - 10
#  - 2
#  - 10
#  - -1
  - 2
  - 3
  - 2
  - 7
  - 2
  - 40

inf_instructs:
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
  - True
  - True
  - True
  - True
  - True
  - True

inf_selections:
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
#  - True
  - True
  - True
  - True
  - True
  - True
  - True

dec_lora: True