ckpt_path: "saved_exp/2024-09-21 08:31:21.655169_125/GOFA/qp3rxlqu/checkpoints/last.ckpt"
load_dir:
last_epochs: 1
num_epochs: 1
grad_acc_step: 32
l2: 0.1
lr: 0.0003
mode: "autoencoder"
load_model: False
save_model:
  save: True
  steps:
  monitor: False
  time: 5
  epochs:
  top_k: -1
  last: True
