data_root_path: "/storage1/yinjie.tang/Active/feng.jiarui/TAGDataset"
load_dir:
ckpt_path:
last_epochs: 0
num_epochs: 1
grad_acc_step: 32
l2: 0.1
lr: 0.0003
mode: "autoencoder"
load_model: False
save_model:
  save: True
  steps:
  monitor: False
  time: 5
  epochs:
  top_k: -1
  last: True
